name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          rm -rf node_modules .next out
          npm install
          npm install -D tailwindcss postcss autoprefixer ts-node csv-parser
          npm install @tremor/react react-icons @headlessui/react @headlessui/tailwindcss

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll
          cp -r .next/static out/_next/static || true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          token: ${{ secrets.GH_TOKEN }}
          clean: true